name: Pierre Vigier
markdown: kramdown
excerpt_separator: <!--more-->
future: true
url: "https://pvigier.github.io"
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
paginate: 5
paginate_path: "/:num/"
jekyll-archives:
  enabled:
    - 'month'
    - 'tags'
  layouts:
    month: month-archive
    tag: tag
  permalinks:
    month: '/:year/:month/'
    tag: '/tag/:name/'
feed:
  path: rss.xml
