name: Pierre Vigier
markdown: kramdown
excerpt_separator: <!--more-->
future: true
gems: [jekyll-paginate, jekyll-archives]
paginate: 5
paginate_path: "/:num/"
jekyll-archives:
        enabled: ['month']
        layouts:
            month: month-archive
        permalinks:
                month: '/:year/:month/'